# Numerical operations focused ensemble
# For testing numerical reasoning capabilities
name: "add"
train_ratio: 0
output_dir: "problems/ensembles"
seed: 42
shuffle: true

problem_specs:

  - family: "numerical_operations"
    difficulty: "hard"
    color_mode: "two_color"
    sample_count: 14