# Numerical operations focused ensemble
# For testing numerical reasoning capabilities
name: "prepend_sequence"
train_ratio: 0.85
output_dir: "problems/ensembles"
seed: 42
shuffle: true

problem_specs:

  - family: "prepend_sequence"
    difficulty: "hard"
    color_mode: "two_color"
    sample_count: 720