# Numerical operations focused ensemble
# For testing numerical reasoning capabilities
name: "symm"
train_ratio: 0
output_dir: "problems/ensembles"
seed: 42
shuffle: true

problem_specs:

  - family: "regex_same_num"
    difficulty: "hard"
    color_mode: "four_color"
    sample_count: 100